micronaut:
  application:
    name: pix

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    chave_pix:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10

datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix #jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: com.mysql.cj.jdbc.Driver #org.h2.Driver
    username: root
    password: root

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
